[package]
name = "docudex-nu"
version = "0.1.0"
authors = ["Caelia R Chapin <crc@caelia.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
